### ISSUE TITLE
COMPILATION ERROR : Variable _1 is already defined in class jooq.steve.db.Keys

### ISSUE THREAD

**Issue by Smoerrebroed** [steve-community/steve#1891]
#### Checklist

- [x] I checked other issues already, but found no answer/solution
- [x] I checked the documentation and wiki, but found no answer/solution
- [x] I am running the latest version and the issue still occurs
- [x] I am sure that this issue is about SteVe (and not about the charging station software or something unrelated to SteVe)

#### Specifications
```
SteVe Version     :  3.9.0
Operating system  :  Linux 6.17.9-arch1-1
JDK               :  OpenJDK 25 and OpenJDK 21
Database          :  MariaDB 12.1.2 (works with SteVe 3.8.0)
```

#### Expected Behavior

1. Run ./mwnv package
2. Package steve.war is generated.

#### Actual Behavior

```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] ./target/generated-sources/jooq/steve/db/Keys.java:[112,89] variable _1 is already defined in class jooq.steve.db.Keys
[ERROR] ./target/generated-sources/jooq/steve/db/Keys.java:[114,106] variable _1 is already defined in class jooq.steve.db.Keys
[ERROR] ./target/generated-sources/jooq/steve/db/Keys.java:[115,89] variable _2 is already defined in class jooq.steve.db.Keys
[ERROR] ./target/generated-sources/jooq/steve/db/Keys.java:[116,96] variable _1 is already defined in class jooq.steve.db.Keys
[ERROR] ./target/generated-sources/jooq/steve/db/Keys.java:[117,84] variable _2 is already defined in class jooq.steve.db.Keys
[ERROR] ./target/generated-sources/jooq/steve/db/Keys.java:[118,83] variable _1 is already defined in class jooq.steve.db.Keys
[ERROR] ./src/main/java/de/rwth/idsg/steve/NotificationFeature.java:[40,22] constructor NotificationFeature in enum de.rwth.idsg.steve.NotificationFeature cannot be applied to given types;
  required: no arguments
  found:    boolean,java.lang.String
  reason: actual and formal argument lists differ in length

```

#### Steps to Reproduce the Problem

  1. Make sure Java 25 (OpenJDK) is installed and configured properly.
  2. Download https://github.com/steve-community/steve/archive/refs/tags/steve-3.9.0.zip
  3. Unzip
  4. Run ./mvnw package in unzipped folder.

#### Additional context

Not sure what this is related to, but I did use the exact same process as for all previous versions - for which it no longer works either btw. (Tested on SteVe 3.8.0 with the same environment.) So perhaps one of the imports has changed?

**Comment by goekay** [comment]
you are trying to compile the project with java 25. java 25 is not tested [with our builds](https://github.com/steve-community/steve/blob/41d2a11b6194154ef2d5896f7718ed859a006fb7/.github/workflows/main.yml#L10).

NotificationFeature has a [lombok](https://projectlombok.org/) annotation for the constructor. i can imagine this being is a lombok-java compatibility issue. 

i had no issues with downloading the release zip file and building it with `./mvnw clean package` with java 21.

**Comment by Smoerrebroed** [comment]
```
$ java --version
openjdk 21.0.9 2025-10-21
OpenJDK Runtime Environment (build 21.0.9+10)
OpenJDK 64-Bit Server VM (build 21.0.9+10, mixed mode, sharing)
```

```
$ mvnw clean package
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] ./target/generated-sources/jooq/steve/db/Keys.java:[112,89] variable _1 is already defined in class jooq.steve.db.Keys
[ERROR] ./target/generated-sources/jooq/steve/db/Keys.java:[114,106] variable _1 is already defined in class jooq.steve.db.Keys
[ERROR] ./target/generated-sources/jooq/steve/db/Keys.java:[115,89] variable _2 is already defined in class jooq.steve.db.Keys
[ERROR] ./target/generated-sources/jooq/steve/db/Keys.java:[116,96] variable _1 is already defined in class jooq.steve.db.Keys
[ERROR] ./target/generated-sources/jooq/steve/db/Keys.java:[117,84] variable _2 is already defined in class jooq.steve.db.Keys
[ERROR] ./target/generated-sources/jooq/steve/db/Keys.java:[118,83] variable _1 is already defined in class jooq.steve.db.Keys
[ERROR] ./src/main/java/de/rwth/idsg/steve/NotificationFeature.java:[40,22] constructor NotificationFeature in enum de.rwth.idsg.steve.NotificationFeature cannot be applied to given types;
  required: no arguments
  found:    boolean,java.lang.String
  reason: actual and formal argument lists differ in length
```

I had already tested with Java 21 (as stated in the JDK versions above) but just made another attempt with a cleanly unzipped source tree - no change as you can see. Any other ideas?

**Comment by goekay** [comment]
could you try with one of the tested mariadb versions?

**Comment by goekay** [comment]
[java 25 is part of the build matrix now](https://github.com/steve-community/steve/actions/runs/19829450817/job/56811391987) and the project can be built. i could not make [mariadb 11.x or 12.y work with github actions](https://github.com/steve-community/steve/commit/f8203b7b368767499cf118e89277b517c24af5b3), though. so, you are in unchartered territory.

**Comment by Smoerrebroed** [comment]
Alright, did some more investigating. Turns out that MariaDB 12.x seemingly doesn't work anymore. (It DID work with SteVe 3.8.0 though.) MariaDB 11.x OTOH seems to work fine for me, so after discovering and fixing a few bugs in the DB dump things are back up again.

Still it would be nice to bring back compatibility with MariaDB 12.x - possibly as an officially supported platform this time. ;-)
